### ISSUE TITLE
The overlay-play will be wrong, when controls multi-players in one page

### ISSUE THREAD

**Issue by edisonh** [2fdevs/bower-videogular-overlay-play#4]
Because of the scope of overlay-play is not isolate.
To fix it:
Add "scope: {}" in the directive define of 'vgOverlayPlay'.

**Comment by 2fdevs** [comment]
Please open issues related with coding to the main repo: https://github.com/2fdevs/videogular

**Comment by edisonh** [comment]
I  create a pull request to this issue

**Comment by 2fdevs** [comment]
Yes, but this repository is only for distribution, I've closed your PR in this repo, please, send your PR to the development repository available here: https://github.com/2fdevs/videogular
