### ISSUE TITLE
IE: Overlay Play Button Icon Does Not Hide Itself On Play

### ISSUE THREAD

**Issue by KKHANBF** [2fdevs/bower-videogular-overlay-play#7]
Hi,

I am having an issue on my development environment that i can replicate on your demo examples.

http://www.videogular.com/examples/overlay-play-plugin/

When you click the big play icon it does not hide it self. Ive only noticed this issue in Internet Explorer. If you focus out of the video after hitting the play icon it then hides it self.

it does hide it self on this example. http://www.videogular.com/examples/creating-a-custom-layer/. I'm not entirely sure whats different as they both use the same overlay plugin.

Is there a fix for this?

**Comment by 2fdevs** [comment]
Hi,

This repository is only for distribution. Can you open this issue in our development repository?
https://github.com/2fdevs/videogular/issues

Please, add your IE version.

Thanks.
